version: '3.8'

services:
  csfc-auth-mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csfc_auth_db
      MYSQL_USER: csfc_user
      MYSQL_PASSWORD: csfc_pass
    ports:
      - "3309:3306"
    volumes:
      - csfc_mysql_data:/var/lib/mysql

volumes:
  csfc_mysql_data: